/**
 * Local filesystem storage driver (ARCHITECTURE.md §3: uploads on the local
 * filesystem in development, behind a storage interface so object storage can
 * replace it later).
 *
 * Keys are generated by the server: "<companyId>/<documentId>.<ext>". A key is
 * validated against that shape and resolved strictly inside the upload
 * directory, so no request-derived text ever becomes a path.
 */

import fs from 'node:fs/promises';
import path from 'node:path';

const KEY_PATTERN = /^cmp_[0-9A-Z]{26}\/doc_[0-9A-Z]{26}\.(pdf|jpg|png|webp|gif|heic)$/;

export function storageKeyFor(companyId, documentId, extension) {
  const key = `${companyId}/${documentId}.${extension}`;
  if (!KEY_PATTERN.test(key)) throw new Error('Refusing to build an invalid storage key.');
  return key;
}

export function createLocalStorage({ rootDir }) {
  const root = path.resolve(rootDir);

  function resolve(key) {
    if (!KEY_PATTERN.test(key)) throw new Error('Invalid storage key.');
    const target = path.resolve(root, key);
    if (!target.startsWith(root + path.sep)) throw new Error('Storage key escapes the upload directory.');
    return target;
  }

  return {
    async save(key, bytes) {
      const target = resolve(key);
      await fs.mkdir(path.dirname(target), { recursive: true });
      // 'wx': never overwrite an existing file.
      await fs.writeFile(target, bytes, { flag: 'wx' });
    },

    /** The stored bytes, or null when the file no longer exists. */
    async read(key) {
      try {
        return await fs.readFile(resolve(key));
      } catch (error) {
        if (error.code === 'ENOENT') return null;
        throw error;
      }
    },

    /** Remove a stored file; a file that is already gone is not an error. */
    async remove(key) {
      await fs.rm(resolve(key), { force: true });
    },
  };
}
